
# Объявления

## Создать новое объявление (5.1)
POST http://localhost:5000/offers/create HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Im1ha2VldmhvbWUzQG92ZXJsb29rLm5ldCIsImlkIjoiNjQ4NDRmZWQxMDI2MjI0MzNmZWFkMWEyIiwiaWF0IjoxNjg2MzkyODQyLCJleHAiOjE2ODY1NjU2NDJ9.oXW-WFyH6u2SQRF8Qfkc3tmooxyCG_eL4gmeonHYAZk

{
  "title": "Чёткая хата7",
  "description": "Один из лучших хостелов для душевного общения. Ужинаем вместе и играем в «Мафию» по вечерам, вкусно готовим. Ежедневная уборка, бесплатный Wi-Fi, чистое постельное белье.",
  "postDate": "2023-05-17T07:47:15.358Z",
  "cityName": "Paris",
  "preview": "apartment-small-03.jpg",
  "photos": [
        "apartment-01.jpg",
        "apartment-02.jpg",
        "apartment-03.jpg",
        "apartment-04.jpg",
        "apartment-small-01.jpg",
        "apartment-small-02.jpg"
    ],
  "isPremium": true,
  "rating": 0,
  "roomsCount": 3,
  "guestsCount": 4,
  "offerType": "house",
  "price": 2971,
  "features": [
        "Fridge"
    ],
  "latitude": 51.225402,
  "longitude": 2.351499
}

###

## Обновить, редактировать объявление (5.2)
PATCH http://localhost:5000/offers/648450d3102622433fead1a5 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Im1ha2VldmhvbWUzQG92ZXJsb29rLm5ldCIsImlkIjoiNjQ4NDRmZWQxMDI2MjI0MzNmZWFkMWEyIiwiaWF0IjoxNjg2MzkyODQyLCJleHAiOjE2ODY1NjU2NDJ9.oXW-WFyH6u2SQRF8Qfkc3tmooxyCG_eL4gmeonHYAZk

{
  "title": "Makeev Alexey test 3"
}

###

## Удаление объявления (5.3)

DELETE http://localhost:5000/offers/6484510c102622433fead1bd HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Im1ha2VldmhvbWUzQG92ZXJsb29rLm5ldCIsImlkIjoiNjQ4NDRmZWQxMDI2MjI0MzNmZWFkMWEyIiwiaWF0IjoxNjg2MzkyODQyLCJleHAiOjE2ODY1NjU2NDJ9.oXW-WFyH6u2SQRF8Qfkc3tmooxyCG_eL4gmeonHYAZk

###

## Получить список предложений по аренде (5.4)
GET http://localhost:5000/offers?limit=10 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Im1ha2VldmhvbWUzQG92ZXJsb29rLm5ldCIsImlkIjoiNjQ4NDRmZWQxMDI2MjI0MzNmZWFkMWEyIiwiaWF0IjoxNjg2NDk4ODQ5LCJleHAiOjE2ODY2NzE2NDl9.8-ilIBZ1nl4zCrDldb-wBeNzUYPN47d7hWLg_Qp8sdI

###

## Детальная информация по предложению (5.5)
GET http://localhost:5000/offers/648450d3102622433fead1a5 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Im1ha2VldmhvbWUzQG92ZXJsb29rLm5ldCIsImlkIjoiNjQ4NDRmZWQxMDI2MjI0MzNmZWFkMWEyIiwiaWF0IjoxNjg2MzkyODQyLCJleHAiOjE2ODY1NjU2NDJ9.oXW-WFyH6u2SQRF8Qfkc3tmooxyCG_eL4gmeonHYAZk

###

## Список комментариев для предложения (5.6)
GET http://localhost:5000/offers/648450d3102622433fead1a5/comments HTTP/1.1

###

## Добавление комментария (5.7)
POST http://localhost:5000/comments HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Im1ha2VldmhvbWUzQG92ZXJsb29rLm5ldCIsImlkIjoiNjQ4NDRmZWQxMDI2MjI0MzNmZWFkMWEyIiwiaWF0IjoxNjg2MzkyODQyLCJleHAiOjE2ODY1NjU2NDJ9.oXW-WFyH6u2SQRF8Qfkc3tmooxyCG_eL4gmeonHYAZk

{
  "text": "Тестовый текст комментария ",
  "offerId": "648450d3102622433fead1a5",
  "rating": 3
}
###

# Пользователи

## Регистрация пользователя (5.8)
POST http://localhost:5000/users/register HTTP/1.1
Content-Type: application/json

{
  "name": "Макеев Алексей3",
  "email": "makeevhome3@overlook.net",
  "avatarUrl": "makeev.png",
  "userType": "pro",
  "password": "ma1234"
}

###

## Авторизация пользователя (5.9)
POST http://localhost:5000/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "makeevhome3@overlook.net",
  "password": "ma1234"
}

###
## Выход из закрытой части приложения (5.10)
DELETE  http://localhost:5000/users/6483176f70ac0e9be5104198/logout HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Im1ha2VldmhvbWUzQG92ZXJsb29rLm5ldCIsImlkIjoiNjQ4NDRmZWQxMDI2MjI0MzNmZWFkMWEyIiwiaWF0IjoxNjg2MzkyODQyLCJleHAiOjE2ODY1NjU2NDJ9.oXW-WFyH6u2SQRF8Qfkc3tmooxyCG_eL4gmeonHYAZk

###

## Проверка состояния пользователя (5.11)
GET  http://localhost:5000/users/login HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Im1ha2VldmhvbWUzQG92ZXJsb29rLm5ldCIsImlkIjoiNjQ4NDRmZWQxMDI2MjI0MzNmZWFkMWEyIiwiaWF0IjoxNjg2MzkyODQyLCJleHAiOjE2ODY1NjU2NDJ9.oXW-WFyH6u2SQRF8Qfkc3tmooxyCG_eL4gmeonHYAZk

###
## Премиальные предложения для города (5.12)
GET http://localhost:5000/offers/premium/Paris HTTP/1.1
###

## Список избранных предложений (5.13)
GET http://localhost:5000/offers/favorite/get HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Im1ha2VldmhvbWUzQG92ZXJsb29rLm5ldCIsImlkIjoiNjQ4NDRmZWQxMDI2MjI0MzNmZWFkMWEyIiwiaWF0IjoxNjg2MzkyODQyLCJleHAiOjE2ODY1NjU2NDJ9.oXW-WFyH6u2SQRF8Qfkc3tmooxyCG_eL4gmeonHYAZk

###

## Добавление предложения в избранное (5.14)
PATCH http://localhost:5000/offers/favorite/648450f8102622433fead1b1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Im1ha2VldmhvbWUzQG92ZXJsb29rLm5ldCIsImlkIjoiNjQ4NDRmZWQxMDI2MjI0MzNmZWFkMWEyIiwiaWF0IjoxNjg2MzkyODQyLCJleHAiOjE2ODY1NjU2NDJ9.oXW-WFyH6u2SQRF8Qfkc3tmooxyCG_eL4gmeonHYAZk

###

## Удаление предложения из избранного (5.14)
DELETE http://localhost:5000/offers/favorite/64845104102622433fead1b9 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Im1ha2VldmhvbWUzQG92ZXJsb29rLm5ldCIsImlkIjoiNjQ4NDRmZWQxMDI2MjI0MzNmZWFkMWEyIiwiaWF0IjoxNjg2MzkyODQyLCJleHAiOjE2ODY1NjU2NDJ9.oXW-WFyH6u2SQRF8Qfkc3tmooxyCG_eL4gmeonHYAZk

###


## Отправка аватарки пользователю

POST http://localhost:5000/users/63d77401a03b664cf3e10556/avatar HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="avatar-max.jpg"
Content-Type: image/png

< mocks/img/avatar-max.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--
###

## Загрузка превью для предложения
POST http://localhost:5000/offers/63d77401a03b664cf3e1055d/previewimage HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Im1ha2VldmhvbWUzQG92ZXJsb29rLm5ldCIsImlkIjoiNjQ4NDRmZWQxMDI2MjI0MzNmZWFkMWEyIiwiaWF0IjoxNjg2MzkyODQyLCJleHAiOjE2ODY1NjU2NDJ9.oXW-WFyH6u2SQRF8Qfkc3tmooxyCG_eL4gmeonHYAZk

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="prevImg"; filename="room.jpg"
Content-Type: image/png

< ./mocks/img/room.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

## Загрузка изображений для предложения
POST http://localhost:5000/offers/63d77401a03b664cf3e1055d/images HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Im1ha2VldmhvbWUzQG92ZXJsb29rLm5ldCIsImlkIjoiNjQ4NDRmZWQxMDI2MjI0MzNmZWFkMWEyIiwiaWF0IjoxNjg2MzkyODQyLCJleHAiOjE2ODY1NjU2NDJ9.oXW-WFyH6u2SQRF8Qfkc3tmooxyCG_eL4gmeonHYAZk


------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="room.jpg"
Content-Type: image/png

< ./mocks/img/room.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="avatar-max.jpg"
Content-Type: image/png

< ./mocks/img/avatar-max.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="apartment-02.jpg"
Content-Type: image/png

< ./mocks/img/apartment-02.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="apartment-01.jpg"
Content-Type: image/png

< ./mocks/img/apartment-01.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--
###
