
# Объявления

## Создать новое объявление (5.1)
POST http://localhost:5000/offers/create HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Im1ha2VldmhvbWVAbWFpbC5uZXQiLCJpZCI6IjY0OTMxODk1Zjg1YWVhNzYzNmNmNDkxYiIsImlhdCI6MTY4NzM2MTcxNCwiZXhwIjoxNjg3NTM0NTE0fQ.qfja3MgiGhlCJcXVDUtTSHJAib565PkDPu8_l4B-3iE

{
  "title": "Чёткая хата 5",
  "description": "Один из лучших хостелов для душевного общения. Ужинаем вместе и играем в «Мафию» по вечерам, вкусно готовим. Ежедневная уборка, бесплатный Wi-Fi, чистое постельное белье.",
  "postDate": "2023-06-17T07:47:15.358Z",
  "cityName": "Paris",
  "preview": "room8.jpg",
  "photos": [
        "room1.jpg",
        "room2.jpg",
        "room3.jpg",
        "room4.jpg",
        "room5.jpg",
        "room6.jpg"
    ],
  "isPremium": true,
  "isFavorite": false,
  "rating": 0,
  "roomsCount": 3,
  "guestsCount": 4,
  "offerType": "house",
  "price": 2971,
  "features": [
        "Fridge"
    ],
  "latitude": 48.8565,
  "longitude": 2.351499
}

###

## Обновить, редактировать объявление (5.2)
PATCH http://localhost:5000/offers/64931db48e81f36950425828 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Im1ha2VldmhvbWVAbWFpbC5uZXQiLCJpZCI6IjY0OTMxODk1Zjg1YWVhNzYzNmNmNDkxYiIsImlhdCI6MTY4NzM2MTcxNCwiZXhwIjoxNjg3NTM0NTE0fQ.qfja3MgiGhlCJcXVDUtTSHJAib565PkDPu8_l4B-3iE

{
  "title": "Makeev Alexey test 1"
}

###

## Удаление объявления (5.3)

DELETE http://localhost:5000/offers/64931957f85aea7636cf492a HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Im1ha2VldmhvbWVAbWFpbC5uZXQiLCJpZCI6IjY0OTMxODk1Zjg1YWVhNzYzNmNmNDkxYiIsImlhdCI6MTY4NzM2MTcxNCwiZXhwIjoxNjg3NTM0NTE0fQ.qfja3MgiGhlCJcXVDUtTSHJAib565PkDPu8_l4B-3iE

###

## Получить список предложений по аренде (5.4)
GET http://localhost:5000/offers?limit=10 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Im1ha2VldmhvbWVAbWFpbC5uZXQiLCJpZCI6IjY0OTMxODk1Zjg1YWVhNzYzNmNmNDkxYiIsImlhdCI6MTY4NzM2MTcxNCwiZXhwIjoxNjg3NTM0NTE0fQ.qfja3MgiGhlCJcXVDUtTSHJAib565PkDPu8_l4B-3iE

###

## Детальная информация по предложению (5.5)
GET http://localhost:5000/offers/64931db48e81f36950425828 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Im1ha2VldmhvbWVAbWFpbC5uZXQiLCJpZCI6IjY0OTMxODk1Zjg1YWVhNzYzNmNmNDkxYiIsImlhdCI6MTY4NzM2MTcxNCwiZXhwIjoxNjg3NTM0NTE0fQ.qfja3MgiGhlCJcXVDUtTSHJAib565PkDPu8_l4B-3iE

###

## Список комментариев для предложения (5.6)
GET http://localhost:5000/offers/64931db48e81f36950425828/comments HTTP/1.1

###

## Добавление комментария (5.7)
POST http://localhost:5000/comments HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Im1ha2VldmhvbWVAbWFpbC5uZXQiLCJpZCI6IjY0OTMxODk1Zjg1YWVhNzYzNmNmNDkxYiIsImlhdCI6MTY4NzM2MTcxNCwiZXhwIjoxNjg3NTM0NTE0fQ.qfja3MgiGhlCJcXVDUtTSHJAib565PkDPu8_l4B-3iE

{
  "text": "Тестовый текст комментария 5",
  "offerId": "64931db48e81f36950425828",
  "rating": 5
}
###

# Пользователи

## Регистрация пользователя (5.8)
POST http://localhost:5000/users/register HTTP/1.1
Content-Type: application/json

{
  "name": "Макеев Алексей",
  "email": "makeevhome@mail.net",
  "avatarUrl": "makeev.png",
  "userType": "pro",
  "password": "2222aa"
}

###

## Авторизация пользователя (5.9)
POST http://localhost:5000/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "makeevhome@mail.net",
  "password": "2222aa"
}

###
## Выход из закрытой части приложения (5.10)
DELETE http://localhost:5000/users/logout HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Im1ha2VldmhvbWVAbWFpbC5uZXQiLCJpZCI6IjY0OTMxODk1Zjg1YWVhNzYzNmNmNDkxYiIsImlhdCI6MTY4NzQxNDMxNiwiZXhwIjoxNjg3NTg3MTE2fQ.EzoLxnS7qtvwcGrvLlgK-r8BgDTvSBoCXcTBmUWL4vw


###

## Проверка состояния пользователя (5.11)
GET  http://localhost:5000/users/login HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Im1ha2VldmhvbWVAbWFpbC5uZXQiLCJpZCI6IjY0OTMxODk1Zjg1YWVhNzYzNmNmNDkxYiIsImlhdCI6MTY4NzM2MTcxNCwiZXhwIjoxNjg3NTM0NTE0fQ.qfja3MgiGhlCJcXVDUtTSHJAib565PkDPu8_l4B-3iE

###
## Премиальные предложения для города (5.12)
GET http://localhost:5000/offers/premium/Paris HTTP/1.1
Content-Type: application/json

###

## Список избранных предложений (5.13)
GET http://localhost:5000/offers/favorite/get HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Im1ha2VldmhvbWVAbWFpbC5uZXQiLCJpZCI6IjY0OTMxODk1Zjg1YWVhNzYzNmNmNDkxYiIsImlhdCI6MTY4NzM2MTcxNCwiZXhwIjoxNjg3NTM0NTE0fQ.qfja3MgiGhlCJcXVDUtTSHJAib565PkDPu8_l4B-3iE

###

## Добавление предложения в избранное (5.14)
POST http://localhost:5000/offers/favorite/get/64931dc88e81f36950425838 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Im1ha2VldmhvbWVAbWFpbC5uZXQiLCJpZCI6IjY0OTMxODk1Zjg1YWVhNzYzNmNmNDkxYiIsImlhdCI6MTY4NzM2MTcxNCwiZXhwIjoxNjg3NTM0NTE0fQ.qfja3MgiGhlCJcXVDUtTSHJAib565PkDPu8_l4B-3iE

###

## Удаление предложения из избранного (5.14)
DELETE http://localhost:5000/offers/favorite/get/64931dc88e81f36950425838 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Im1ha2VldmhvbWVAbWFpbC5uZXQiLCJpZCI6IjY0OTMxODk1Zjg1YWVhNzYzNmNmNDkxYiIsImlhdCI6MTY4NzM2MTcxNCwiZXhwIjoxNjg3NTM0NTE0fQ.qfja3MgiGhlCJcXVDUtTSHJAib565PkDPu8_l4B-3iE

###


## Отправка аватарки пользователю

POST http://localhost:5000/users/649066da856f0181cf2b7dde/avatar HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Im1ha2VldmhvbWVAbWFpbC5uZXQiLCJpZCI6IjY0OTMxODk1Zjg1YWVhNzYzNmNmNDkxYiIsImlhdCI6MTY4NzM2MTcxNCwiZXhwIjoxNjg3NTM0NTE0fQ.qfja3MgiGhlCJcXVDUtTSHJAib565PkDPu8_l4B-3iE

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="image.png"
Content-Type: image/png

< ./static/default-avatar2.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--
###

## Загрузка превью для предложения
POST http://localhost:5000/offers/648b0e178cebc7577cdf5cb9/previewimage HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Im1ha2VldmhvbWVAbWFpbC5uZXQiLCJpZCI6IjY0OTMxODk1Zjg1YWVhNzYzNmNmNDkxYiIsImlhdCI6MTY4NzM2MTcxNCwiZXhwIjoxNjg3NTM0NTE0fQ.qfja3MgiGhlCJcXVDUtTSHJAib565PkDPu8_l4B-3iE

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="preview"; filename="room.jpg"
Content-Type: image/jpeg

< ./static/room8.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

## Загрузка изображений для предложения
POST http://localhost:5000/offers/64930a7b5a225ae3d496ee01/images HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Im1ha2VldmhvbWVAbWFpbC5ydSIsImlkIjoiNjQ5MDY2ZGE4NTZmMDE4MWNmMmI3ZGRlIiwiaWF0IjoxNjg3MzU4MDM2LCJleHAiOjE2ODc1MzA4MzZ9.DUnHw9jrZj3AqcJVzbeorJGoxHOWY5i48xLPZoa0CAk


------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="photos"; filename="room1.jpg"
Content-Type: image/jpeg

< ./static/room1.jpg

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="photos"; filename="room2.jpg"
Content-Type: image/jpeg

< ./static/room2.jpg

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="photos"; filename="room3.jpg"
Content-Type: image/jpeg

< ./static/room3.jpg

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="photos"; filename="room4.jpg"
Content-Type: image/jpeg

< ./static/room4.jpg

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="photos"; filename="room5.jpg"
Content-Type: image/jpeg

< ./static/room5.jpg

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="photos"; filename="room6.jpg"
Content-Type: image/jpeg

< ./static/room6.jpg

------WebKitFormBoundary7MA4YWxkTrZu0gW--


###
